### PR TITLE
fix(myinfo): generate base string straight from params

### LINKED ISSUE #457: [MyInfo] incorrect baseString for signature verification
# **Describe the bug**
The [`baseString` generator](https://github.com/opengovsg/mockpass/blob/master/lib/crypto/myinfo-signature.js#L34-L68) currently hardcodes the template, which results in a verification failure.

There is an implementation over at the [MyInfo Helper](https://github.com/GovTechSG/singpass-myinfo-oidc-helper/blob/master/src/util/SigningUtil.ts#L80-L89) for reference.

### `POST` request (`token`)
helper `baseString`
```
POST&http://localhost:5156/myinfo/v3/token&app_id=CNX&client_id=CNX&client_secret=[...]&code=[...]&grant_type=authorization_code&nonce=166780413703300&redirect_uri=http://localhost:8000/auth/profile/edit&signature_method=RS256&state=uU3tXeRyrhOLyLZm&timestamp=1667804137033
```

mockpass `baseString` (missing `state` param)
```
POST&http://localhost:5156/myinfo/v3/token&app_id=CNX&client_id=CNX&client_secret=[...]&code=[...]&grant_type=authorization_code&nonce=166780413703300&redirect_uri=http://localhost:8000/auth/profile/edit&signature_method=RS256&timestamp=1667804137033
```

### `GET` request (`person`)
helper `baseString`
```
GET&http://localhost:5156/myinfo/v3/person/S***/&app_id=CNX&attributes=uinfin,name,regadd,email,mobileno&client_id=CNX&nonce=166780366263900&signature_method=RS256&sp_esvcId=MYINFO-CONSENTPLATFORM&timestamp=1667803662639
```

mockpass `baseString` (missing `sp_esvcId` param)
```
GET&http://localhost:5156/myinfo/v3/person/S***/&app_id=CNX&attributes=uinfin,name,regadd,email,mobileno&client_id=CNX&nonce=166780366263900&signature_method=RS256&timestamp=1667803662639 
```

# **Additional context**
I can fix it if I have some spare capacity, but not anytime this week unfortunately.

### PR DESCRIPTION
**Pull request by LoneRifle**
## Problem

Fixes #457

cc @randName for review

### CODE REVIEW

File: lib/express/myinfo/controllers.js [hunk 1]
```diff
@@ -132,15 +132,11 @@ module.exports =
...
       }),
       (req, res) => {
-        const [tokenTemplate, redirectURI] =
-          consent.authorizations[req.body.code]
+        const [tokenTemplate] = consent.authorizations[req.body.code]
         const [, authHeader] = (req.get('Authorization') || '').split(' ')
 
         const { signature, baseString } = MYINFO_SECRET
-          ? myInfoSignature(authHeader, req, {
-              clientSecret: MYINFO_SECRET,
```
Comment (randName) [inline lib/express/myinfo/controllers.js:141]: doesn't `client_secret` still need to go in?

Comment (randName) [reply lib/express/myinfo/controllers.js:141]: oh right it's part of query params already. ignore me haha

**Review by randName — APPROVED** [review]

**Comment by randName** [comment]
lgtm. thanks!

File: lib/express/myinfo/controllers.js (hunk 1 above)
Comment (LoneRifle) [reply lib/express/myinfo/controllers.js:141]: it might be, but I realised that for a realistic mock, we should compare the signature against one generated from a base string containing what mockpass knows as the client secret. I'm patching this now.
